---
-
  hosts: all

  vars:
    postgresql:
      version: 9.1

  tasks:

    - name: add postgres repositories
      sudo: true
      lineinfile:
        dest=/etc/apt/sources.list
        line="deb http://apt.postgresql.org/pub/repos/apt/ squeeze-pgdg main"
        backup=yes
        insertafter=EOF

    - name: pg keys
      shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
      sudo: true

    - name: apt update
      apt: update_cache=yes cache_valid_time=3600
      sudo: true

    - name: install packages
      apt: pkg={{ item }} state=installed
      sudo: true
      with_items:
        - curl
        - vim
        - git
        - runit
        - postgresql-{{ postgresql.version }}
        - redis-server
        - mysql-server
        - mysql-client
        - libcurl4-openssl-dev
        - libmysql-ruby
        - libmysqlclient-dev
        - libpq-dev
        - libxslt1-dev

    - name: rvm install test
      shell: curl -sSL https://get.rvm.io | bash -s stable --ruby --autolibs=enabled
        creates=~/.rvm/rubies/

    - name: make postgres user as god
      lineinfile:
        dest=/etc/postgresql/{{ postgresql.version }}/main/pg_hba.conf
        regexp=".*local.*all.*postgres.*peer.*"
        line="local all postgres trust"
        state=present
        backup=yes
      sudo: true

    - name: restart postgresql
      service: name=postgresql state=restarted
      sudo: true
