---
-
  hosts: all

  tasks:
    - name: apt update
      apt: update_cache=yes cache_valid_time=3600
      sudo: true

    - name: install packages
      apt: pkg={{ item }} state=installed
      sudo: true
      with_items:
        - curl
        - vim
        - git
        - runit
        - postgresql
        - redis-server
        - mysql-server
        - mysql-client
        - libcurl4-openssl-dev
        - libmysql-ruby
        - libmysqlclient-dev
        - libpq-dev

    - name: rvm install test
      shell: curl -sSL https://get.rvm.io | bash -s stable --ruby --autolibs=enabled
        creates=~/.rvm/rubies/
