---
-
  hosts: all

  vars:
    ruby_version: 2.0.0

  roles:
    - zzet.postgresql

  tasks:

    - name: apt update
      apt: update_cache=yes cache_valid_time=3600
      sudo: true

    - name: install packages
      apt: pkg={{ item }} state=installed
      sudo: true
      with_items:
        - curl
        - vim
        - git
        - runit
        - redis-server
        - mysql-server
        - mysql-client
        - libcurl4-openssl-dev
        - libmysql-ruby
        - libmysqlclient-dev
        - libpq-dev
        - libxslt1-dev

    - name: rvm install
      shell: curl -sSL https://get.rvm.io | bash -s stable --ruby={{ruby_version}} --autolibs=enabled
        creates=~/.rvm/rubies/default/
